[build]
builder = "DOCKERFILE"
dockerfilePath = "ehrbase/Dockerfile"

[deploy]
healthcheckPath = "/management/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
