[build]
builder = "DOCKERFILE"
dockerfilePath = "ehrbase/Dockerfile"

[deploy]
healthcheckPath = "/ehrbase/rest/status"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
